[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = true

[programs.devnet]
ApeOrDie = "Ks6N2eSijgaQ6Gjpjc78M6deX8LrngprTPt5zxombdK"

[registry]
url = "https://staked.helius-rpc.com/?api-key=67ea9085-1406-4db8-8872-38ac77950d7a"

[provider]
cluster = "Devnet"
wallet = "./wallet-keypair.json"

[scripts]
accept_authority = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/acceptAuthority.ts"
change_vault_exec = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/changeVaultExec.ts"
change_vault_manager = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/changeVaultManager.ts"
check_config = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/checkConfig.ts"
init_ApeOrDie = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initApeOrDie.ts"
launch_token = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/launchToken.ts"
post_deploy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/post-deploy.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_change_claimer = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/changeClaimer.ts"
test_claim = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/claim.ts"
test_deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/deposit.ts"
test_init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initRayVault.ts"
test_nft_balance = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/checkBalance.ts"
test_withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/withdraw.ts"
update_state = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/updateState.ts"
listen-events = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listenEvents.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://staked.helius-rpc.com/?api-key=67ea9085-1406-4db8-8872-38ac77950d7a"
ledger = ".anchor/test-ledger"
rpc_port = 8899
